export { default as CTA } from "./CTA"
export { default as Footer } from "./Footer"
export { default as Hero } from "./Hero"
export { default as Navbar } from "./Navbar"
export { default as Process } from "./Process"
export { default as Services } from "./Services"
export { default as TradeTicker } from "./TradeTicker"
